name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js 15
#         uses: actions/setup-node@v1
#         with:
#           node-version: 15
#       - run: npm ci
#       - run: npm run build
#       - run: npm test

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLONE_9A3E0 }}"
          channelId: live
          projectId: clone-9a3e0
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
